server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: ${SPRING_APP_NAME:discovery-server}

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}

    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}

  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:false}